openapi: "3.0.2"
info:
  title: REST APIサンプル
  description: REST APIのサンプルアプリ
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  "/users":
    get:
      description: ユーザー一覧
      operationId: UserIndex
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
    post:
      description: ユーザー投稿
      operationId: UserCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - "name"
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
  "/users/{id}":
    get:
      description: ユーザー詳細
      operationId: UserShow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ユーザーID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
    patch:
      description: ユーザー更新
      operationId: UserUpdate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ユーザーID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - "name"
              properties:
                name:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
    delete:
      description: ユーザー削除
      operationId: UserDelete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ユーザーID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time

  "/posts":
    get:
      description: 投稿一覧
      operationId: PostIndex
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  title:
                    type: string
                  context:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
  "/posts/{id}":
    get:
      description: 投稿詳細
      operationId: PostShow
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 投稿ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  title:
                    type: string
                  context:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
  "/users/{user_id}/posts":
    post:
      description: 投稿保存
      operationId: PostCreate
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
          description: ユーザーID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  title:
                    type: string
                  context:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
